version: "3.4"

networks:
  default:

services:
  api:
    container_name: medical-api
    expose:
      - 8080
    ports:
      - "8080:8080"
    build:
      context: medical_api
      dockerfile: deployment/server/Dockerfile
      target: dev
      args:
        RUN_LEVEL: dev
    volumes:
      - ./medical_api:/opt/app
    networks:
      - default
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      - mongo
      - redis
      - neo4j

  mongo:
    container_name: medical-mongo
    image: library/mongo:4.2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: medical
    networks:
      - default
    volumes:
      - ./.docker_data/mongo:/data/db
      - ./docker-init/mongo:/docker-entrypoint-initdb.d

  neo4j:
    container_name: medical-neo4j
    image: neo4j:4.0.3
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .docker_data/neo4j:/var/lib/neo4j/data
    environment:
      NEO4J_AUTH: neo4j/password

  redis:
    container_name: medical-redis
    image: library/redis:6
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
    - ./.docker_data/redis:/var/lib/redis

  nginx:
    container_name: medical-nginx
    expose:
      - 80
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - api
    networks:
      - default
